- name: Instalando Sprint Tool Suite
  vars:
   - sts_release = '4.9.0.RELEASE'

  get_url:
    url: https://download.springsource.com/release/STS4/{{ sts_release }}/dist/e4.18/spring-tool-suite-4-{{ sts_release }}-e4.18.0-linux.gtk.x86_64.tar.gz
    dest: /home/ambiente/install/
    mode: '0440'
